### ISSUE TITLE
Crash when using Khurakan planet pack & Industrial Overhaul (mod compatibility issue)

### ISSUE THREAD

**Issue by padthaitofuhot** [padthaitofuhot/se-configurable-ores#16]
[1:25 PM] ABITCRAZY: Hi Team, I would like to seek help for below errors which cause the game is unable to load with configurable-ores loaded into the mod list.
```
2023-06-13 01:17:40.654 - Thread:   1 ->  ORE[]> SESSION > -=] Configurable Ores v1.0.15.0 (Mod ID 2973891097) [=-
2023-06-13 01:17:40.654 - Thread:   1 ->  ORE[]> SESSION > https://steamcommunity.com/sharedfiles/filedetails/?id=2973891097
2023-06-13 01:17:40.654 - Thread:   1 ->  ORE[]> SESSION > Initialize(¯\_(ツ)_/¯)
2023-06-13 01:17:40.657 - Thread:   1 ->  ORE[SP]> CONFIG > [BEGIN] Load configuration
2023-06-13 01:17:40.657 - Thread:   1 ->  ORE[SP]> CONFIG > No config present, creating default config.
2023-06-13 01:17:40.658 - Thread:   1 ->  ORE[SP]> CONFIG > [BEGIN] Create default configuration
2023-06-13 01:17:40.659 - Thread:   1 ->  ORE[SP]> CONFIG > [END] Create default configuration
2023-06-13 01:17:40.697 - Thread:   1 ->  Error: Error during loading session:System.NullReferenceException: Object reference not set to an instance of an object.
   at ConfigurableOres.Helpers.LogVar[T](String prefix, String name, T varT, Boolean isServer)
   at ConfigurableOres.MyPlanetConfiguration.LogVar[T](String name, T varT, Boolean isServer)
   at ConfigurableOres.MyPlanetConfiguration.GenerateMappings()
   at ConfigurableOres.MyPlanetConfiguration..ctor(IEnumerable`1 planetOreMappings)
   at ConfigurableOres.ConfigurableOres.LoadAndCheckPlanetConfigurations()
   at ConfigurableOres.ConfigurableOres.LoadData()
   at Sandbox.Game.World.MySession.LoadComponent(MySessionComponentBase component)
   at Sandbox.Game.World.MySession.LoadDataComponents()
   at Sandbox.Game.World.MySession.PrepareBaseSession(MyObjectBuilder_Checkpoint checkpoint, MyObjectBuilder_Sector sector)
   at Sandbox.Game.World.MySession.Load(String sessionPath, MyObjectBuilder_Checkpoint checkpoint, UInt64 checkpointSizeInBytes, Boolean saveLastStates, Boolean allowXml)
2023-06-13 01:17:40.698 - Thread:   1 ->  ERROR: Loading screen failed
```
[1:25 PM] ABITCRAZY:
```
2023-06-13 01:17:40.702 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at ConfigurableOres.Helpers.LogVar[T](String prefix, String name, T varT, Boolean isServer)
   at ConfigurableOres.MyPlanetConfiguration.LogVar[T](String name, T varT, Boolean isServer)
   at ConfigurableOres.MyPlanetConfiguration.GenerateMappings()
   at ConfigurableOres.MyPlanetConfiguration..ctor(IEnumerable`1 planetOreMappings)
   at ConfigurableOres.ConfigurableOres.LoadAndCheckPlanetConfigurations()
   at ConfigurableOres.ConfigurableOres.LoadData()
   at Sandbox.Game.World.MySession.LoadComponent(MySessionComponentBase component)
   at Sandbox.Game.World.MySession.LoadDataComponents()
   at Sandbox.Game.World.MySession.PrepareBaseSession(MyObjectBuilder_Checkpoint checkpoint, MyObjectBuilder_Sector sector)
   at Sandbox.Game.World.MySession.Load(String sessionPath, MyObjectBuilder_Checkpoint checkpoint, UInt64 checkpointSizeInBytes, Boolean saveLastStates, Boolean allowXml)
   at Sandbox.Game.World.MySessionLoader.<>c__DisplayClass18_0.<LoadSingleplayerSessionInternal>b__6()
   at System.DelegateExtensions.InvokeIfNotNull(Action handler)
   at Sandbox.Game.Gui.MyGuiScreenLoading.RunLoad()
```
[1:27 PM] ABITCRAZY: I am using this mod with now only Insturial Overhaul & World Scenario - Khurakan (https://steamcommunity.com/sharedfiles/filedetails/?id=2852224218) , these are the only mod and world scenario), any clues? (edited)
Steam Workshop::The Khurakan System

[1:28 PM] ABITCRAZY: Thanks,  please TAG me for any reply.  Thanks a lot with much appreciation.
[10:52 PM] ABITCRAZY: I will try to remove planets from the world scenario one by one tonight and see if anyway to fix, if anyone guide me a fix method also welcomed.

**Comment by padthaitofuhot** [comment]
ABITCRAZY is using both Industrial Overhaul and Khurakan mods together.

I requested that they ensure CO is above IO and Khurakan in mod load order.
